apiVersion: v1
kind: Pod
metadata:
  labels:
    adhoc: mkmahtoq7
  name: adhocpod7
spec:
  containers:
  - image: alpine
    name: adhocpod7
    command: ["/bin/shsh","-c","while true; do date>>/mnt/date.txt; sleep 3; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
