apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhhocdepmkmahto5
  labels:
    adhoc: mkmahtoq5
spec:
  replicas: 3
  selector:
    matchLabels:
      adhoc: mkmahtoq5
  template:
    metadata:
      labels:
        adhoc: mkmahtoq5
    spec:
       containers:
        - env:
          - name: x
            value: app2
          image: mkmahto7/webapp2:v1
          imagePullPolicy: Always
          name: adhocpod2
          ports:
          - containerPort: 80
