apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: mkmahtoq9
  name: jenkinspod1
spec:
  containers:
  - image: jenkins/jenkins
    name: jenkinspod1
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
