apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: mkmahto2q3
  name: adhocpod2
spec:
  nodeSelector:
    kubernetes.io/hostname: ip-172-31-41-104.ec2.internal
  containers:
  - env:
    - name: x
      value: app2
    image: mkmahto7/webapp2:v1
    name: adhocpod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

